name: myproject

services:
  backserver:
    build:
      context: ./server     # ชี้ไปที่โฟลเดอร์ server
    env_file:
      - ./server/.env        # ใช้ .env จาก host
    image: myback
    restart: always
    container_name: mybackcon
    ports:
      - "5000:5000"

  web:
    build:
      context: ./client
      args:
        REACT_API_URL: http://3.107.26.249:5000/api
    env_file:
      - ./client/.env        # ใช้ .env จาก host
    image: myweb
    container_name: mywebcon
    restart: always
    ports:
      - "3000:3000"

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      # - ./data:/data/db
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    restart: always

volumes:
  mongo-data: 
  mongo-configdb:

